name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "30 18 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest

    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          SHOW_TIME: true
          SHOW_TIME_RANGE: true
          SHOW_TOTAL: true
          TIME_RANGE: all_time
          LANG_COUNT: 5
          STOP_AT_OTHER: true
